version:  "2"
services:
    proxy:
        image: httpd
        depends_on:
          - web
    web:
        image: php
        ports:
          - "80:8080"
        depends_on:
          - mysql
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example