version:  "2"
services:
    proxy:
        image: httpd
        depends_on:
          - web
    web:
        image: microsoft/dotnet:sdk
        ports:
          - "80:8080"
        depends_on:
          - sqlserver
    mysql:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"